### ISSUE TITLE
PostgreSQL 17 support

### ISSUE THREAD

**Issue by devrimgunduz** [bigsql/plprofiler#21]
Hi,

This PR needs to be applied for v17 compatibility. Can you please take a look? We also will need a new release for v17 packages.. Thanks!

https://github.com/bigsql/plprofiler/pull/19/commits

Regards, Devrim

**Comment by luss** [comment]
thanks devrim, will do.

**Comment by devrimgunduz** [comment]
Any updates?

**Comment by luss** [comment]
sorry i'll taker a look today.

**Comment by luss** [comment]
It's fixed...  Now documented to support pg13 thru pg17 with REL4_2_5

**Comment by devrimgunduz** [comment]
Thanks a lot!

**Comment by luss** [comment]
The latest version now supports thru pg17.  I got a chance to apply the PR
and update the doc a little bit.
