### ISSUE TITLE
Issue with PLPROFILER

### ISSUE THREAD

**Issue by elangodba** [bigsql/plprofiler#7]
Hi Guys,

Am Configuring **PLPROFILER on RHEL8 to support aurora postgres database 11.9.**
Am Encountering the below error in every environment configured. If we exclude --output parameter the error doesnt occur.

Googling around doesn't give me much of a solution.

_Traceback (most recent call last):
File "/usr/local/bin/plprofiler", line 11, in <module>
load_entry_point('plprofiler==4.1', 'console_scripts', 'plprofiler')()
File "/usr/local/lib/python3.6/site-packages/plprofiler/plprofiler_tool.py", line 75, in main
return run_command(sys.argv[2:])
File "/usr/local/lib/python3.6/site-packages/plprofiler/plprofiler_tool.py", line 844, in run_command
report_data = plp.get_local_report_data(opt_name, opt_top, args)
File "/usr/local/lib/python3.6/site-packages/plprofiler/plprofiler.py", line 403, in get_local_report_data
raise Exception("No profiling data found")
Exception: No profiling data found_

References:

https://www.percona.com/blog/2019/02/13/plprofiler-getting-a-handy-tool-for-profiling-your-pl-pgsql-code/
https://dzone.com/articles/plprofiler-getting-a-handy-tool-for-profiling-your-1

**Comment by wieck** [comment]
* did you include plprofiler in `shared_preload_libraries`?
* did you actually run any PL code to profile? ("No profiling data found" tells me you didn't)
* did you run the profiler report request against the same database that you ran the PL code in?

**Comment by wieck** [comment]
Closing the issue due to lack of response.

**Comment by luss** [comment]
As an FYI.   I think the profiler may only be supported in aurora postgres for versions 12 and above.  In any event, that error looks like the user has got to run some pl code to profile.
